// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InternalUnzipRootsFunc is an autogenerated mock type for the UnzipRootsFunc type
type InternalUnzipRootsFunc struct {
	mock.Mock
}

type InternalUnzipRootsFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalUnzipRootsFunc) EXPECT() *InternalUnzipRootsFunc_Expecter {
	return &InternalUnzipRootsFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: zipBytes
func (_m *InternalUnzipRootsFunc) Execute(zipBytes []byte) ([]byte, error) {
	ret := _m.Called(zipBytes)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(zipBytes)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(zipBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(zipBytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InternalUnzipRootsFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type InternalUnzipRootsFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - zipBytes []byte
func (_e *InternalUnzipRootsFunc_Expecter) Execute(zipBytes interface{}) *InternalUnzipRootsFunc_Execute_Call {
	return &InternalUnzipRootsFunc_Execute_Call{Call: _e.mock.On("Execute", zipBytes)}
}

func (_c *InternalUnzipRootsFunc_Execute_Call) Run(run func(zipBytes []byte)) *InternalUnzipRootsFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *InternalUnzipRootsFunc_Execute_Call) Return(pemBytes []byte, err error) *InternalUnzipRootsFunc_Execute_Call {
	_c.Call.Return(pemBytes, err)
	return _c
}

func (_c *InternalUnzipRootsFunc_Execute_Call) RunAndReturn(run func([]byte) ([]byte, error)) *InternalUnzipRootsFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewInternalUnzipRootsFunc creates a new instance of InternalUnzipRootsFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalUnzipRootsFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalUnzipRootsFunc {
	mock := &InternalUnzipRootsFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
