name: On Every Commit

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      - name: Unit Test
        run: make test-unit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config ./configs/golangci.yaml --timeout=3m
